### PR TITLE
Add systemd unit files

### PR DESCRIPTION
**Pull request by agrare**
Depends on:
- [x] https://github.com/iv1111/manageiq-providers-ibm_power_vc/pull/4
- [x] https://github.com/iv1111/manageiq-providers-ibm_power_vc/pull/6

### CODE REVIEW

**Comment by iv1111** [comment]
Says 

```
ActiveRecord::RecordInvalid:
       Validation failed: ManageIQ::Providers::Openstack::CloudManager::Template: Vendor is not included in the list
```

I've changed the vendor name to _power_vc_. Can that be the reason?
```

  def self.vm_vendor
    "power_vc"
  end

  def image_name
    self.class.vm_vendor
  end
```

**Comment by agrare** [comment]
Yes, that would do it.

**Comment by iv1111** [comment]
Looks good. Do I merge it?

**Comment by agrare** [comment]
@iv1111 so I built this on top of the other PRs listed in the depends section.  Would be best to merge them in order (#4 then #6)

**Pull request merged**
